version: "3.3"
services:
  besu-node1:
    build:
      context: .
      dockerfile: ./bootnode/Dockerfile
    environment:
      - NODE_INDEX=1
      - RPC_PORT=8545
      - RPC_WS_PORT=8546
      - P2P_PORT=30303
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
  besu-node2:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    environment:
      - NODE_INDEX=2
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8547
      - RPC_WS_PORT=5468
      - P2P_PORT=30304
    ports:
      - 8547:8547
      - 8548:8548
      - 30304:30304
    depends_on:
      - besu-node1
  besu-node3:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    environment:
      - NODE_INDEX=3
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8549
      - RPC_WS_PORT=8550
      - P2P_PORT=30305
    ports:
      - 8549:8549
      - 8550:8550
      - 30305:30305
    depends_on:
      - besu-node1
  besu-node4:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    environment:
      - NODE_INDEX=4
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8551
      - RPC_WS_PORT=8552
      - P2P_PORT=30306
    ports:
      - 8551:8551
      - 8552:8552
      - 30306:30306
    depends_on:
      - besu-node1
