name: Test
on: [push, pull_request]
jobs:

  besu4:
    name: 4 validators
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./pkg/...

    - name: Resolve dependencies
      run: npm install

    - name: apply the patch
      run: sed -i -e 's/20000,/200000,/' ./node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js

    - name: compile
      run: npx truffle compile

    - name: Setup 4 besu nodes
      run: NO_GEN_CODE=1 ./scripts/setup.sh besu4

    - name: E2E test
      run: make e2e-test
